name: Check If Docs Test Is Up To Date

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

defaults:
  run:
    shell: bash

env:
  DATA_DIR: .github/docs_test_data.json

jobs:
  check_if_docs_test_was_changed:
    name: Check If Docs Test Was Changed
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout The Ockam Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          path: ockam
          fetch-depth: 0
          repository: build-trust/ockam
          ref: metaclips/automate_cli_docs
        
      - name: Checkout The Ockam Documentation Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          path: ockam-documentation
          fetch-depth: 0
        
      - name: Check The Current Commit SHA Of The Docs Bats Test
        run: |
          cd ockam
          docs_test_sha=$(git rev-parse --short=8 HEAD -- implementations/rust/ockam/ockam_command/tests/bats/use_cases.bats)
          # Check if the sha exists in the file
          if ! cat ${{ github.workspace }}/ockam-documentation/${{ env.DATA_DIR }} | grep "$docs_test_sha"; then
            exit 1
          fi
